// 安全与隐私功能类型定义

// 端到端加密
export interface E2EEncryption {
  id: string;
  userId: string;
  enabled: boolean;
  keyPair: KeyPairInfo;
  encryptedData: EncryptedDataTypes;
  trustedDevices: TrustedDevice[];
  recoveryOptions: RecoveryOption[];
  auditLog: SecurityAuditEntry[];
}

export interface KeyPairInfo {
  publicKey: string;
  privateKeyHash: string;
  algorithm: 'RSA-4096' | 'ECDSA-P256' | 'Ed25519';
  createdAt: Date;
  expiresAt: Date;
  rotationReminder: boolean;
  lastRotation: Date;
}

export interface EncryptedDataTypes {
  playlists: boolean;
  listeningHistory: boolean;
  searchHistory: boolean;
  messages: boolean;
  downloads: boolean;
  preferences: boolean;
  paymentInfo: boolean;
}

export interface TrustedDevice {
  id: string;
  name: string;
  type: DeviceType;
  os: string;
  browser?: string;
  lastAccess: Date;
  firstAccess: Date;
  location: string;
  ipAddress: string;
  trusted: boolean;
  current: boolean;
  publicKey: string;
}

export type DeviceType = 'phone' | 'tablet' | 'desktop' | 'tv' | 'speaker' | 'car' | 'wearable';

export interface RecoveryOption {
  id: string;
  type: 'email' | 'phone' | 'recovery_key' | 'trusted_contact';
  value: string;
  verified: boolean;
  lastUsed?: Date;
}

export interface SecurityAuditEntry {
  id: string;
  timestamp: Date;
  action: SecurityAction;
  deviceId: string;
  ipAddress: string;
  location: string;
  success: boolean;
  details: string;
}

export type SecurityAction =
  | 'login'
  | 'logout'
  | 'password_change'
  | 'key_rotation'
  | 'device_added'
  | 'device_removed'
  | 'data_export'
  | 'data_delete'
  | 'permission_change';

// 匿名模式
export interface AnonymousMode {
  id: string;
  userId: string;
  enabled: boolean;
  settings: AnonymousSettings;
  pseudonym: Pseudonym;
  dataHandling: DataHandling;
  networkSettings: NetworkPrivacy;
  visibilitySettings: VisibilitySettings;
}

export interface AnonymousSettings {
  hideListeningActivity: boolean;
  hideProfile: boolean;
  hideFromSearch: boolean;
  useProxy: boolean;
  stripMetadata: boolean;
  randomizeTimestamps: boolean;
  disableAnalytics: boolean;
  disablePersonalization: boolean;
}

export interface Pseudonym {
  enabled: boolean;
  name: string;
  avatar: string;
  autoGenerated: boolean;
  rotationEnabled: boolean;
  rotationInterval: number; // days
}

export interface DataHandling {
  localOnly: boolean;
  autoDelete: boolean;
  deleteAfterDays: number;
  minimizeCollection: boolean;
  excludeFromTraining: boolean;
  noCloudSync: boolean;
}

export interface NetworkPrivacy {
  vpnEnabled: boolean;
  vpnServer?: string;
  torEnabled: boolean;
  dnOverHttps: boolean;
  blockTrackers: boolean;
  customDns?: string;
}

export interface VisibilitySettings {
  profileVisibility: 'public' | 'friends' | 'private';
  activityVisibility: 'public' | 'friends' | 'private';
  playlistVisibility: 'public' | 'friends' | 'private';
  followersVisibility: 'public' | 'friends' | 'private';
  onlineStatus: boolean;
  lastActiveVisible: boolean;
}

// 家长控制
export interface ParentalControls {
  id: string;
  parentUserId: string;
  childAccountId: string;
  enabled: boolean;
  pin: string;
  settings: ParentalSettings;
  schedules: UsageSchedule[];
  reports: UsageReport[];
  approvalQueue: ApprovalRequest[];
  notifications: ParentalNotification[];
}

export interface ParentalSettings {
  explicitContent: ExplicitContentSettings;
  socialFeatures: SocialRestrictions;
  purchaseRestrictions: PurchaseRestrictions;
  contentFilters: ContentFilter[];
  timeRestrictions: TimeRestriction;
  ageRating: AgeRating;
}

export interface ExplicitContentSettings {
  allowExplicit: boolean;
  filterExplicitLyrics: boolean;
  hideExplicitContent: boolean;
  replaceWithClean: boolean;
  notifyParent: boolean;
}

export interface SocialRestrictions {
  allowMessaging: boolean;
  allowFriendRequests: boolean;
  allowPublicProfile: boolean;
  allowComments: boolean;
  allowSharing: boolean;
  allowCollaborativePlaylists: boolean;
  approvalRequired: boolean;
}

export interface PurchaseRestrictions {
  allowPurchases: boolean;
  maxAmount: number;
  requireApproval: boolean;
  approvalThreshold: number;
  allowSubscriptions: boolean;
  allowGifting: boolean;
}

export interface ContentFilter {
  id: string;
  type: 'keyword' | 'genre' | 'artist' | 'topic';
  value: string;
  action: 'block' | 'warn' | 'notify';
}

export interface TimeRestriction {
  enabled: boolean;
  dailyLimit: number; // minutes
  weeklyLimit: number;
  quietHours: QuietHours[];
  schoolDayRestrictions: boolean;
  weekendBonus: number;
}

export interface QuietHours {
  start: string; // HH:mm
  end: string;
  days: number[];
  enforced: boolean;
}

export interface AgeRating {
  birthDate: Date;
  ageVerified: boolean;
  maxRating: 'G' | 'PG' | 'PG13' | 'R' | 'NC17';
  autoAdjust: boolean;
}

export interface UsageSchedule {
  id: string;
  name: string;
  type: 'daily' | 'weekly' | 'custom';
  slots: TimeSlot[];
  enabled: boolean;
}

export interface TimeSlot {
  day: number;
  startTime: string;
  endTime: string;
  allowedDuration: number;
}

export interface UsageReport {
  id: string;
  period: 'daily' | 'weekly' | 'monthly';
  startDate: Date;
  endDate: Date;
  totalListeningTime: number;
  topGenres: GenreUsage[];
  topArtists: ArtistUsage[];
  topSongs: SongUsage[];
  blockedAttempts: BlockedAttempt[];
  screenTime: ScreenTimeData;
  recommendations: ParentalRecommendation[];
}

export interface GenreUsage {
  genre: string;
  time: number;
  percentage: number;
}

export interface ArtistUsage {
  artistId: string;
  artistName: string;
  time: number;
  plays: number;
}

export interface SongUsage {
  songId: string;
  songName: string;
  artistName: string;
  plays: number;
  time: number;
}

export interface BlockedAttempt {
  timestamp: Date;
  type: string;
  content: string;
  reason: string;
}

export interface ScreenTimeData {
  totalTime: number;
  activeTime: number;
  backgroundTime: number;
  sessions: number;
  averageSession: number;
  longestSession: number;
}

export interface ParentalRecommendation {
  type: 'positive' | 'concern' | 'suggestion';
  title: string;
  description: string;
  action?: string;
}

export interface ApprovalRequest {
  id: string;
  type: 'friend' | 'purchase' | 'content' | 'feature';
  description: string;
  requestedAt: Date;
  status: 'pending' | 'approved' | 'denied';
  decidedAt?: Date;
  details: Record<string, any>;
}

export interface ParentalNotification {
  id: string;
  type: 'limit_reached' | 'blocked_content' | 'new_friend' | 'purchase' | 'concern';
  message: string;
  timestamp: Date;
  read: boolean;
  actionRequired: boolean;
  action?: string;
}

// 数据隐私
export interface DataPrivacy {
  id: string;
  userId: string;
  dataInventory: DataInventory;
  consents: Consent[];
  dataRequests: DataRequest[];
  deletionRequests: DeletionRequest[];
  exportHistory: ExportRecord[];
  privacyDashboard: PrivacyDashboard;
}

export interface DataInventory {
  categories: DataCategory[];
  lastUpdated: Date;
  totalSize: string;
  retentionPolicies: RetentionPolicy[];
}

export interface DataCategory {
  id: string;
  name: string;
  description: string;
  types: DataType[];
  shared: boolean;
  sharingPartners: string[];
  retentionDays: number;
  deletable: boolean;
}

export interface DataType {
  name: string;
  description: string;
  collected: boolean;
  required: boolean;
  purpose: string[];
  lastAccessed: Date;
}

export interface RetentionPolicy {
  category: string;
  duration: number;
  reason: string;
  autoDelete: boolean;
}

export interface Consent {
  id: string;
  category: string;
  name: string;
  description: string;
  required: boolean;
  granted: boolean;
  grantedAt?: Date;
  expiresAt?: Date;
  version: string;
}

export interface DataRequest {
  id: string;
  type: 'access' | 'rectification' | 'portability';
  status: 'pending' | 'processing' | 'completed' | 'denied';
  createdAt: Date;
  completedAt?: Date;
  categories: string[];
  format?: string;
  downloadUrl?: string;
  expiresAt?: Date;
}

export interface DeletionRequest {
  id: string;
  categories: string[];
  status: 'pending' | 'processing' | 'completed' | 'partial';
  createdAt: Date;
  scheduledFor: Date;
  completedAt?: Date;
  retained: RetainedData[];
  reason?: string;
}

export interface RetainedData {
  category: string;
  reason: string;
  retainedUntil: Date;
}

export interface ExportRecord {
  id: string;
  createdAt: Date;
  format: 'json' | 'csv' | 'html';
  categories: string[];
  size: string;
  downloadUrl: string;
  expiresAt: Date;
  downloaded: boolean;
}

export interface PrivacyDashboard {
  overallScore: number;
  recommendations: PrivacyRecommendation[];
  recentActivity: PrivacyActivity[];
  thirdPartyAccess: ThirdPartyAccess[];
  dataUsageStats: DataUsageStats;
}

export interface PrivacyRecommendation {
  id: string;
  priority: 'high' | 'medium' | 'low';
  title: string;
  description: string;
  action: string;
  impact: string;
}

export interface PrivacyActivity {
  timestamp: Date;
  type: string;
  description: string;
  risk: 'low' | 'medium' | 'high';
}

export interface ThirdPartyAccess {
  id: string;
  name: string;
  logo: string;
  type: 'app' | 'service' | 'partner';
  permissions: string[];
  connectedAt: Date;
  lastAccess: Date;
  revokeUrl: string;
}

export interface DataUsageStats {
  totalDataPoints: number;
  dataShared: number;
  dataRetained: number;
  thirdPartyShares: number;
  anonymizedData: number;
}

// 安全设置
export interface SecuritySettings {
  id: string;
  userId: string;
  authentication: AuthenticationSettings;
  sessionManagement: SessionSettings;
  loginAlerts: LoginAlertSettings;
  accountRecovery: AccountRecoverySettings;
  securityQuestions: SecurityQuestion[];
  trustedContacts: TrustedContact[];
}

export interface AuthenticationSettings {
  passwordStrength: number;
  passwordLastChanged: Date;
  twoFactorEnabled: boolean;
  twoFactorMethods: TwoFactorMethod[];
  biometricEnabled: boolean;
  biometricTypes: BiometricType[];
  passkeysEnabled: boolean;
  passkeys: Passkey[];
}

export interface TwoFactorMethod {
  type: 'totp' | 'sms' | 'email' | 'hardware_key' | 'push';
  enabled: boolean;
  primary: boolean;
  lastUsed?: Date;
  backup?: string;
}

export type BiometricType = 'fingerprint' | 'face' | 'iris' | 'voice';

export interface Passkey {
  id: string;
  name: string;
  deviceType: string;
  createdAt: Date;
  lastUsed: Date;
}

export interface SessionSettings {
  maxSessions: number;
  sessionTimeout: number;
  rememberDevice: boolean;
  autoLogout: boolean;
  singleDeviceMode: boolean;
  activeSessions: ActiveSession[];
}

export interface ActiveSession {
  id: string;
  device: string;
  location: string;
  ipAddress: string;
  startedAt: Date;
  lastActivity: Date;
  current: boolean;
}

export interface LoginAlertSettings {
  enabled: boolean;
  newDevice: boolean;
  newLocation: boolean;
  failedAttempts: boolean;
  suspiciousActivity: boolean;
  notificationMethods: string[];
}

export interface AccountRecoverySettings {
  recoveryEmail: string;
  recoveryPhone?: string;
  recoveryKey: boolean;
  recoveryKeyHint?: string;
  trustedDeviceRecovery: boolean;
}

export interface SecurityQuestion {
  id: string;
  question: string;
  answerHash: string;
}

export interface TrustedContact {
  id: string;
  name: string;
  email: string;
  verified: boolean;
  canRecover: boolean;
  addedAt: Date;
}

// 威胁检测
export interface ThreatDetection {
  id: string;
  userId: string;
  enabled: boolean;
  alerts: ThreatAlert[];
  blockedThreats: BlockedThreat[];
  riskScore: number;
  lastScan: Date;
  settings: ThreatDetectionSettings;
}

export interface ThreatAlert {
  id: string;
  type: ThreatType;
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  timestamp: Date;
  resolved: boolean;
  action: string;
  details: Record<string, any>;
}

export type ThreatType =
  | 'suspicious_login'
  | 'brute_force'
  | 'session_hijack'
  | 'phishing'
  | 'malware'
  | 'data_breach'
  | 'unauthorized_access'
  | 'account_takeover';

export interface BlockedThreat {
  id: string;
  type: ThreatType;
  source: string;
  blockedAt: Date;
  details: string;
}

export interface ThreatDetectionSettings {
  autoBlock: boolean;
  alertThreshold: 'low' | 'medium' | 'high';
  vpnDetection: boolean;
  geoBlocking: boolean;
  blockedCountries: string[];
  rateLimit: number;
  bruteForceProtection: boolean;
}
